version: 2
jobs:
  run_test_case:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    restore_cache:
        keys:
          - v1-dependencies-{{ checksum "yarn.lock"}}
    steps:
        - checkout
        - run:
            name: Install Deps
            command: yarn
        - save_cache:
            paths:
                - node_modules
            key: v1-dependencies-{{ checksum "yarn.lock"}}
        # - run:
        #     name: Run Tests
        #     command: yarn test
        - run: yarn build
        - store_artifacts:
               path: build
workflows:
  version: 2
  test:
      jobs:
       - run_test_case
       filters:
         branches:
             only:
                - master-branch
