version: 2
jobs:
  run_test_case:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    restore_cache:
        keys:
           - v1-dependencies-{{ checksum "yarn.lock" }} 
    steps:
        - checkout
        - run:
            name: Install Deps
            command: yarn
        - run:
            name: Run tests
            command: yarn test
        - save_cache:
            paths:
                - node_modules
                key: v1-dependencies-{{ checksum "yarn.lock" }}
        - store_artifacts:
             path:build
workflows:
  version: 2
  test:
      jobs:
       - run_test_case
